### ISSUE TITLE
有没有考虑过和Dubbo社区合作，做原生Nebula/gRPC和Dubbo的互通？

### ISSUE THREAD

**Issue by chickenlj** [grpc-nebula/grpc-nebula-java#2]
1. 当前Dubbo已经能初步集成了gRPC框架（尚未发布）。
2. 在1的基础上，我们可以考虑基于NameResolver实现和gRPC体系的互发现；NameResolver在这个nebula中应该已经做了挺多工作了。

**Comment by chickenlj** [comment]
https://github.com/chickenlj/dubbo-samples/tree/gRPC

https://github.com/chickenlj/dubbo/tree/gRPC

**Comment by shoppingsee** [comment]
> 1. 当前Dubbo已经能初步集成了gRPC框架（尚未发布）。
> 2. 在1的基础上，我们可以考虑基于NameResolver实现和gRPC体系的互发现；NameResolver在这个nebula中应该已经做了挺多工作了。

我看到你增加了一个dubbo-rpc-grpc的子项目，你的这个新特性将会推送给 apache/dubbo 吗？

**Comment by chickenlj** [comment]
> 我看到你增加了一个dubbo-rpc-grpc的子项目，你的这个新特性将会推送给 apache/dubbo 吗？

是的，上面的链接分别是继承Dubbo框架的扩展，使用示例，将来会尝试合并入Dubbo主干。

有了dubbo-rpc-grpc后，使用者就可以以Dubbo的编程和配置风格使用gRPC了，同样其他服务治理能力也得以支持。具体使用示例可以参见https://github.com/chickenlj/dubbo-samples/tree/gRPC/dubbo-samples-grpc

在这种情况下面临一个问题，即Dubbo如何与原生的gRPC或者与Nebula互通，协议层面是完全没问题的因为大家用的都是gRPC，主要是如何实现地址自动发现：
1.  Dubbo作为provider，gRPC或者Nebula作为Consumer如何发现Dubbo实例。
2.  gRPC或Nebula作为provider，Dubbo作为Consumer如何发现gRPC实例。

对于以上两种场景，Nebula做的对于DNS和Zookeeper支持，我认为都可以作为很好的参考实现。
