### ISSUE TITLE
有考虑支持JDK11吗？

### ISSUE THREAD

**Issue by jackeylu** [grpc-nebula/grpc-nebula-java#5]
请问有计划升级到支持JDK 11 吗？当前项目的gradle是4.9版本的，也是与JDK 11不兼容。grpc-java目前已经升级成Gradle 6.5.1，代码也已经支持JDK 11了。

**Comment by shoppingsee** [comment]
目前的基准代码与社区的grpc-java 1.17.x保持一致。项目会定期提升基准代码版本，提升基准代码版本后就可以支持JDK 11。
